cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2445p442.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2445p440.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2446p437.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2449p442.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2449p440.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/244/tractor-2443p437.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/245/tractor-2450p437.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/245/tractor-2452p440.fits /global/homes/j/jaehyeon/HSC-5
cp /global/project/projectdirs/cosmo/work/legacysurvey/dr6/tractor/245/tractor-2452p442.fits /global/homes/j/jaehyeon/HSC-5
