cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p047.fits /global/homes/j/jaehyeon/
