cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0064m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0064m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m052.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m055.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066m057.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0068m040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0068m042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0048p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0051p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0053p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0056p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/005/tractor-0058p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0061p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0063p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/006/tractor-0066p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0026p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/002/tractor-0028p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0031p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0033p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0036p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/003/tractor-0038p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0041p050.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p032.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p035.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p037.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p040.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p042.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p045.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p047.fits /global/homes/j/jaehyeon/
cp /global/project/projectdirs/cosmo/data/legacysurvey/dr5/tractor/004/tractor-0043p050.fits /global/homes/j/jaehyeon/
